version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:lld@db:5432/dofushame
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=dofushame
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lld
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
